export const GET_WORKFLOWS = 'GET_WORKFLOWS';
export const GET_WORKFLOW_PROGRESSIONS = 'GET_WORKFLOW_PROGRESSIONS';
export const ADD_WORKFLOW = 'ADD_WORKFLOW';
export const DELETE_WORKFLOW = 'DELETE_WORKFLOW';
export const WORKFLOWS_LOADING = 'WORKFLOWS_LOADING';

export const NEXT_PROGRESSION = 'NEXT_PROGRESSION';
export const PREV_PROGRESSION = 'PREV_PROGRESSION';
export const UPDATE_PROGRESSION_STATUS = 'UPDATE_PROGRESSION_STATUS';
export const GET_PROGRESSION = 'GET_PROGRESSION';
export const ADD_PROGRESSION = 'ADD_PROGRESSION';
export const DELETE_PROGRESSION = 'DELETE_PROGRESSION';
export const PROGRESSIONS_LOADING = 'PROGRESSIONS_LOADING';

export const GET_IMAGES = 'GET_IMAGES';
export const ADD_IMAGE = 'ADD_IMAGE';
export const DELETE_IMAGE = 'DELETE_IMAGE';
export const IMAGES_LOADING = 'IMAGES_LOADING';